image: python:2.7

before_script:
  - ./install_dependencies.sh
  - pushd bin
  - ./apprec.py --init
  - ./apprec.py --train
  - popd

test:
  script:
    - python setup.py test
    - python setup.py build
    - sudo python setup.py install
