image: gabrielssilva/apprecommender:base

before_script:
  - ./install_dependencies.sh
  - pushd bin
  - python --version
  - /usr/bin/python2 apprec.py --init
  - /usr/bin/python2 apprec.py --train
  - popd

test:
  script:
    - /usr/bin/python2 setup.py test
    - /usr/bin/python2 setup.py build
    - /usr/bin/python2 setup.py install
