language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - python-apt
      - python-scipy
      - python-sklearn
      - python-stemmer

virtualenv:
  system_site_packages: true

install:
  - sudo apt-get install debtags
  - pip install -r requirements.txt
  - pip install -U scikit-learn
  - sudo update-apt-xapian-index

before_script:
  - pushd bin
  - ./apprec.py --init
  - ./apprec.py --train
  - popd

script:
  - python setup.py test
